language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: testing
      script: npm run test:ci


